### ISSUE TITLE
Not working with libreelec/ubuntu on odroid-c2

### ISSUE THREAD

**Issue by malomehi** [loboris/Odroid-installer#1]
I tried several times to use this tool on odroid c2 to have both ubuntu and libreelec.
Ubuntu can be booted as many times as you want but once you try to boot libreelec the device crashes on the boot screen and the boot menu no longer works.
The emmc/sd card needs to be re-flashed in order to recover the device.

**Comment by KingDuckZ** [comment]
how did you even install libreelec? It comes as a .img and not as a tar, as the readme assumes.

**Comment by malomehi** [comment]
Solved.
